// Generated by @unpunnyfuns/swatchbook-addon. Do not edit.
export {};
declare module '@unpunnyfuns/swatchbook-addon/hooks' {
  interface SwatchbookTokenMap {
    "az.color.brand.bloom": string;
    "az.color.brand.blue": string;
    "az.color.brand.red": string;
  }

  export type SwatchbookPermutationName = "default";
}
