// Generated by @unpunnyfuns/swatchbook-addon. Do not edit.
export {};
declare module '@unpunnyfuns/swatchbook-addon/hooks' {
  interface SwatchbookTokenMap {
    "az.color.arroyo-blue": string;
    "az.color.azurite": string;
    "az.color.bloom": string;
    "az.color.blue": string;
    "az.color.bougainvillea": string;
    "az.color.brand.arroyo-blue": string;
    "az.color.brand.azurite": string;
    "az.color.brand.bloom": string;
    "az.color.brand.blue": string;
    "az.color.brand.bougainvillea": string;
    "az.color.brand.brick": string;
    "az.color.brand.caliche": string;
    "az.color.brand.chili": string;
    "az.color.brand.cloud": string;
    "az.color.brand.rain": string;
    "az.color.brand.red": string;
    "az.color.brand.saguaro": string;
    "az.color.brand.shade": string;
    "az.color.brand.sonoran-red": string;
    "az.color.brand.tinta": string;
    "az.color.brand.white": string;
    "az.color.brick": string;
    "az.color.caliche": string;
    "az.color.chili": string;
    "az.color.cloud": string;
    "az.color.rain": string;
    "az.color.red": string;
    "az.color.saguaro": string;
    "az.color.semantic.action.destructive.default": string;
    "az.color.semantic.action.destructive.focus-ring": string;
    "az.color.semantic.action.destructive.hover": string;
    "az.color.semantic.action.primary.default": string;
    "az.color.shade": string;
    "az.color.sonoran-red": string;
    "az.color.tinta": string;
    "az.color.white": string;
    "az.component.button.border.radius": string;
    "az.component.button.border.width": string;
    "az.component.button.color.destructive": string;
    "az.component.button.color.destructive-focus-ring": string;
    "az.component.button.color.destructive-hover": string;
    "az.component.button.color.primary": string;
    "az.component.button.disabled.opacity": string;
    "az.component.button.font.size": string;
    "az.component.button.font.weight": string;
    "az.component.button.padding.x": string;
    "az.component.button.padding.y": string;
    "az.component.button.size.lg.font.size": string;
    "az.component.button.size.lg.padding.x": string;
    "az.component.button.size.lg.padding.y": string;
    "az.component.button.size.sm.font.size": string;
    "az.component.button.size.sm.padding.x": string;
    "az.component.button.size.sm.padding.y": string;
  }

  export type SwatchbookPermutationName = "default";
}
