// Generated by @unpunnyfuns/swatchbook-addon. Do not edit.
export {};
declare module '@unpunnyfuns/swatchbook-addon/hooks' {
  interface SwatchbookTokenMap {
    "color.az.blue": string;
    "color.az.red": string;
  }

  export type SwatchbookPermutationName = "default";
}
