// PROOF OF CONCEPT (surface modes). Builds dist/tokens.dark.css from
// tokens.dark.json, which holds only the semantic tokens whose value changes
// in dark mode. Brand colors, primitives, and component tokens never change;
// component tokens alias semantic tokens, so they follow the mode.
//
// Applying a mode: put data-az-surface on any element (the page or a section).
// - data-az-surface="dark": always dark.
// - data-az-surface="auto": dark when the OS is in dark mode.
// - data-az-surface="light": light, e.g. a light section inside a dark page.
// tokens.css re-declares every token on each [data-az-surface] element, so
// aliases recompute inside it; this file then overrides the semantic layer.

import { writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

const dir = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const sd = new StyleDictionary({
  include: [resolve(dir, 'tokens.json')],
  source: [resolve(dir, 'tokens.dark.json')],
  log: { verbosity: 'silent' },
  platforms: {
    css: {
      transformGroup: 'css',
      files: [{
        destination: 'tokens.dark.css',
        format: 'css/variables',
        // Only the tokens tokens.dark.json overrides.
        filter: (token) => token.isSource,
        options: { selector: '[data-az-surface="dark"]', showFileHeader: false, outputReferences: true },
      }],
    },
  },
});

const [{ output }] = await sd.formatPlatform('css');
const declarations = output.slice(output.indexOf('{') + 1, output.lastIndexOf('}')).trimEnd();

await writeFile(
  resolve(dir, 'dist/tokens.dark.css'),
  `/* PROOF OF CONCEPT: placeholder dark mode values. Generated by scripts/build-modes.mjs from tokens.dark.json. */\n` +
    `[data-az-surface="dark"] {${declarations}\n}\n\n` +
    `@media (prefers-color-scheme: dark) {\n  [data-az-surface="auto"] {${declarations.replace(/\n/g, '\n  ')}\n  }\n}\n`,
);
console.log('✔︎ dist/tokens.dark.css');
