// Builds src/generated/tokens.ts from @az-digital/tokens' tokens.json.
//
// Web components render in a shadow root and must work on a page that loads no
// Arizona CSS at all, so a bare `var(--az-…)` isn't enough: with no tokens.css
// on the page it resolves to nothing. Each token here is a var() chain that
// follows the token's own aliases and ends in its resolved value:
//
//   var(--az-component-button-solid-container-color,
//     var(--az-color-semantic-action-default,
//       var(--az-color-brand-red, #ab0520)))
//
// A page that loads tokens.css, or overrides any one layer of the chain, wins;
// a page that loads nothing still gets the design system's value.
//
// The exported object has the same shape as tokens.vars.js
// (`az.component.button.solid.container.color`), so a token is referenced the
// same way in every JavaScript output.

import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

const __dirname = dirname(fileURLToPath(import.meta.url));
const tokensDir = resolve(__dirname, '../../tokens');

const camelCase = (value) => value.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
const ALIAS = /^\{([^}]+)\}$/;

function buildTree(dictionary) {
  const byPath = new Map(dictionary.allTokens.map((token) => [token.path.join('.'), token]));

  const chain = (token) => {
    const alias = typeof token.original.$value === 'string' && token.original.$value.match(ALIAS);
    const target = alias && byPath.get(alias[1]);
    const fallback = target ? chain(target) : token.$value;
    return `var(--${token.name}, ${fallback})`;
  };

  const tree = {};
  for (const token of dictionary.allTokens) {
    let node = tree;
    const keys = token.path.slice(1).map(camelCase);
    keys.slice(0, -1).forEach((key) => (node = node[key] ??= {}));
    node[keys.at(-1)] = chain(token);
  }
  return tree;
}

const sd = new StyleDictionary({
  source: [resolve(tokensDir, 'tokens.json')],
  log: { verbosity: 'silent' },
  hooks: {
    formats: {
      'typescript/web-component-tokens': ({ dictionary }) =>
        `// Generated by scripts/build-tokens.mjs from packages/tokens/tokens.json. Don't edit.\n` +
        `export const az = ${JSON.stringify(buildTree(dictionary), null, 2)} as const;\n`,
    },
  },
  platforms: {
    webComponents: {
      transformGroup: 'css',
      buildPath: resolve(__dirname, '../src/generated') + '/',
      files: [{ destination: 'tokens.ts', format: 'typescript/web-component-tokens' }],
    },
  },
});

await sd.buildAllPlatforms();
